/**
 * GENERATED by scripts/gen-native-stats.mjs — do not edit.
 *
 *   npm run stats:native
 *
 * What native speech scores, per phone, under this exact model build. A
 * learner's GOP is meaningless on its own (§4.6): /a/ is distinctive and
 * always scores near 0, while /r/, /ɾ/ and /l/ crowd each other even for
 * natives. These are the numbers that turn a margin in nats into "2.4σ below
 * where natives sit", and `p05` is the line a verdict is cut on.
 *
 * Regenerate whenever the model build changes (`model-source.json`), or the
 * z-scores shift under the app: the quantization bias only cancels when the
 * reference and the runtime are the same weights (§10.3).
 *
 * Source: google/fleurs es_419 (dev), CC BY 4.0
 * Model:  wav2vec2-xlsr-53-espeak-cv-ft-q4f16
 * Corpus: 165 clips, 20004 phone spans
 * Run:    2026-09-06
 */

import type { PhoneStat } from "./gop";

/** Per phone, for the phones with enough observations to be worth a distribution. */
export const NATIVE_GOP: Readonly<Record<string, PhoneStat>> = {
  "a": { mean: 5.1741, sd: 1.959, n: 2562, p05: 1.9018 },
  "b": { mean: 2.5831, sd: 1.6684, n: 476, p05: -1.7299 },
  "d": { mean: 4.5092, sd: 2.2332, n: 890, p05: -0.7567 },
  "e": { mean: 4.5152, sd: 1.999, n: 2744, p05: 0.5786 },
  "f": { mean: 4.9623, sd: 0.9864, n: 165, p05: 4.0067 },
  "g": { mean: 2.0172, sd: 2.2795, n: 183, p05: -3.407 },
  "i": { mean: 5.3226, sd: 1.539, n: 1063, p05: 2.4963 },
  "j": { mean: 3.016, sd: 1.7908, n: 459, p05: -0.3849 },
  "ʝ": { mean: -1.76, sd: 2.361, n: 101, p05: -6.3053 },
  "k": { mean: 5.1135, sd: 1.7752, n: 817, p05: 2.9296 },
  "l": { mean: 6.3655, sd: 1.2334, n: 1109, p05: 4.9973 },
  "m": { mean: 6.1696, sd: 1.0238, n: 605, p05: 4.363 },
  "n": { mean: 5.8328, sd: 2.2809, n: 1444, p05: 0.1537 },
  "ɲ": { mean: 2.0139, sd: 1.2464, n: 40, p05: -0.0799 },
  "o": { mean: 4.6664, sd: 1.2791, n: 1784, p05: 2.9747 },
  "p": { mean: 5.1707, sd: 1.0374, n: 533, p05: 4.0147 },
  "r": { mean: 0.4118, sd: 0.8677, n: 113, p05: -0.876 },
  "ɾ": { mean: 2.7722, sd: 2.1128, n: 1014, p05: -0.9344 },
  "s": { mean: 4.7977, sd: 1.8306, n: 2117, p05: 1.3211 },
  "t": { mean: 5.2406, sd: 1.2958, n: 957, p05: 3.0192 },
  "tʃ": { mean: 2.7922, sd: 1.6134, n: 60, p05: 2.3709 },
  "u": { mean: 4.5118, sd: 1.5248, n: 448, p05: 1.2589 },
  "w": { mean: 2.2467, sd: 2.9067, n: 192, p05: -4.4252 },
  "x": { mean: 3.5675, sd: 2.1172, n: 128, p05: 2.0809 },
};

/** Every span pooled, for a phone that did not make the cut. Better than no calibration. */
export const NATIVE_POOLED: PhoneStat = { mean: 4.7291, sd: 2.1147, n: 20004, p05: 0.3432 };

export const NATIVE_STATS_META = {
  "model": "wav2vec2-xlsr-53-espeak-cv-ft-q4f16",
  "generated": "2026-09-06",
  "clips": 165,
  "spans": 20004,
  "source": "google/fleurs es_419 (dev), CC BY 4.0"
} as const;
